name: OSV-Scanner

on:
  schedule:
    - cron: '37 9 * * 5'  # Schedule to run every Friday at 09:37 UTC
  workflow_dispatch:  # Manual trigger

permissions:
  security-events: write
  contents: read

jobs:
  scan-scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run OSV-Scanner
        id: scan
        run: |
          osv-scanner -r --skip-git ./ || echo "Vulnerabilities found but continuing workflow"
        continue-on-error: true  # Continue even if the scan fails

      - name: Upload SARIF results
        if: always()  # Ensure this runs even if the previous step fails
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./osv-output.sarif
