name: Security Audit
on:
  pull_request:
    paths:
      - Cargo.lock
  push:
    branches:
      - main
    paths:
      - Cargo.lock
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run security audit
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true 

      - name: Upload audit result
        uses: actions/upload-artifact@v3
        with:
          path: .

      - name: Upload SARIF file to Security tab
        if: always() 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: audit.sarif 
