name: Security Audit
on:
  pull_request:
    paths:
      - Cargo.lock
  push:
    branches:
      - main
    paths:
      - Cargo.lock
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload audit result
        uses: actions/upload-artifact@v3
        with:
          path: .

      - name: Upload SARIF file to Security tab
        if: always()  # Ensure this step runs even if vulnerabilities are found
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: audit.sarif  # Assuming audit-check generates this file
